feature: allow multiple tags in service health query, as api supports since consul 1.3.0
criteo-forks/py-consul pull request #34
Opened 2020-12-02 14:47 UTC by andreasnanko

Did not want to break backwards compatibility, so I did not change the param and made it possible to use string as in the past or a list for multiple tag params.

2020-12-02 16:09 UTC, pierrecdn requested changes
Hi and thanks for that!
Could you reword a bit your commit title to avoid exceeding 80 chars?
Like "feature: allow multiple tags in service health query", and the rest in the commit body ?

2020-12-02 16:09 UTC, pierrecdn commented on consul/base.py
> +                if not isinstance(tag, (list)):
Do you need these parentheses? `isinstance(tag, list)`

2020-12-03 13:06 UTC, pierrecdn commented
Hi,
Thanks, could you merge the two commits into one, and change the commit title as requested?

2020-12-03 13:58 UTC, andreasnanko commented
Should be resolved now.

2020-12-03 15:31 UTC, merged