Support deregister field in Check.script
criteo-forks/py-consul pull request #37
Opened 2020-12-16 16:01 UTC by mougams

2020-12-16 16:24 UTC, pierrecdn requested changes
I think you've pushed way to much commits here. Missing a rebase on upstream?

2020-12-16 16:25 UTC, pierrecdn commented on consul/base.py
> +    def script(klass, args, interval, deregister=None):
Shouldn't we keep the exact same semantic, ie. name the argument `deregister_critical_service_after`?

2020-12-16 16:29 UTC, pierrecdn commented on consul/base.py
> +    def script(klass, args, interval, deregister=None):
Hmm, OK you can forget this request, since it's not this way for other checks (http, tcp).

2020-12-17 09:38 UTC, mougams commented
> I think you've pushed way to much commits here. Missing a rebase on upstream?

It is now fixed

2020-12-17 10:02 UTC, pierrecdn approved these changes

2020-12-17 10:09 UTC, merged